### ISSUE TITLE
Intro Level Hare

### ISSUE THREAD

**Issue by nathanaellesdalons** [floriangamillscheg/burning-arctic#2]
# Task list for intro hare level 1

## Prefabs to create 
- [ ] Cracked/thin Ice ?
- [x] Artic Hare
- [x] Infobox

## Scripts
- [x] Switching Script
- [x] Moving Camera ? (common to the two levels)
- [ ] Adapt Stats Script

## Level components (Riddles)
- [x] Frees the Hare
- [x] Event when free + cinematic
- [x] Create the House 
- [x] Add Exit condition
- [ ] Change infoBox depending on animal/situation
- [ ] Create Level End

## Information
- [x] how do arctic hares live? – decrease of habitat through climate change
- [x] what do hares eat? – gives info about hare health
- [x] data about arctic hare population and development – with regards to human influence
